### ISSUE TITLE
Is there functionality to check if any bank holidays exist within a date range?

### ISSUE THREAD

**Issue by DocTolly** [citco/carbon#3]
Firstly, this is a very helpful package!

I am looking for functionality to explicitly tell me if any bank holidays exist between two specific dates?

For example, I envisage something like this (pseudocode) 
```
$start = Carbon::create(1/2/2019);
$end = Carbon::create(1/7/19);

$start->hasBankHolidayBefore($end); //boolean
//Will output true if a bank holiday exists between the dates, false if a bank holiday does not exist.
```

Does anything like this exist?

Thank you

**Comment by misagh** [comment]
Hi, thanks!

It's been implemented and you can use it by writing this:

```
$start = Carbon::now();
$end = Carbon::now()->subYear(1);
$holidays = $start->bankHolidaysSince($end);
// Will output an empty array or an array containing the list of holidays
```

**Comment by DocTolly** [comment]
@misagh thank you for your time releasing this so quickly! 
It’s a tidy solution! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
