### ISSUE TITLE
Call to undefined function Citco\easter_days()

### ISSUE THREAD

**Issue by benrolfe** [citco/carbon#4]
On **PHP 7.2** I get this error when running `$date->isBankHoliday()`

`Call to undefined function Citco\easter_days()`

How can this be resolved? Is there a fallback if the function doesn't exist?

**Comment by misagh** [comment]
It seems that your PHP has been compiled without the calendar support.

More information: https://stackoverflow.com/questions/5297894/fatal-error-call-to-undefined-function-easter-date/51609625
