### ISSUE TITLE
Bump composer.json from Carbon 2.* to >2 

### ISSUE THREAD

**Issue by radzi00** [citco/carbon#8]
Hi there.
Main nesbot/Carbon package is already at 3.4.
Will there be an issue to update the composer.json to accept nesbot/carbon: >2 (or <4), instead of just 2.* ?
There should not be any breaking changes for this (very useful!) wrapper.
Thank you!
radzi00

**Comment by misagh** [comment]
Hi radzi00

New version had been released:
https://github.com/citco/carbon/tree/3.0.0

Regards
